"""Historical failure analyzer for the constitutional amendment process.

Scans ``pipeline/data/runs/*.json`` to detect when the same protected test
repeatedly blocks independent tasks.  When a test exceeds the threshold,
an amendment proposal is written for human review.

No LLM calls — pure file I/O and counting.
"""

import json
import logging
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path

from ..constants import AMENDMENT_FAILURE_THRESHOLD, AMENDMENT_WINDOW_DAYS
from .failure_parser import parse_test_failures

logger = logging.getLogger(__name__)


def _load_proposals(path: str) -> list[dict]:
    """Load existing amendment proposals, or return an empty list."""
    p = Path(path)
    if p.exists():
        try:
            return json.loads(p.read_text())
        except (json.JSONDecodeError, OSError):
            logger.warning("Could not read %s — starting fresh", path)
    return []


def _save_proposals(proposals: list[dict], path: str) -> None:
    """Persist proposals to JSON."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(proposals, indent=2))


def _render_concerns_md(proposals: list[dict], path: str) -> None:
    """Write a human-readable concerns file from pending proposals."""
    pending = [p for p in proposals if p.get("status") == "pending"]
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Agent Concerns",
        "",
        "> Auto-generated by the amendment analyzer. Do not edit manually.",
        "> To act on a proposal, update its status in "
        "`pipeline/data/amendment_proposals.json`.",
        "",
    ]

    if not pending:
        lines.append("No pending amendment proposals.")
        p.write_text("\n".join(lines) + "\n")
        return

    lines.append(f"## Pending Amendment Proposals ({len(pending)})")
    lines.append("")

    for prop in pending:
        pid = prop["id"]
        test_file = prop["test_file"]
        test_name = prop["test_name"]
        category = prop["category"]
        distinct = prop["distinct_task_count"]
        first = prop["first_seen"]
        last = prop["last_seen"]
        snippet = prop.get("error_snippet", "")
        summaries = prop.get("failing_task_summaries", [])

        lines.append(f"### {pid}: {test_file}::{test_name}")
        lines.append("")
        lines.append(f"- **Category:** {category} test")
        lines.append(f"- **Distinct tasks blocked:** {distinct}")
        lines.append(f"- **Window:** {first} to {last}")
        if snippet:
            lines.append(f"- **Error:** `{snippet}`")
        if summaries:
            lines.append("- **Blocked tasks:**")
            for s in summaries:
                lines.append(f"  - {s}")
        lines.append("")
        lines.append(
            "**Action:** Review whether this test still reflects the contract.  "
            'Set status to `"resolved"` (after updating the test) or '
            '`"dismissed"` in `pipeline/data/amendment_proposals.json`.'
        )
        lines.append("")
        lines.append("---")
        lines.append("")

    p.write_text("\n".join(lines) + "\n")


def analyze_and_propose(
    runs_dir: str,
    output_json: str,
    concerns_md: str,
    *,
    threshold: int = AMENDMENT_FAILURE_THRESHOLD,
    window_days: int = AMENDMENT_WINDOW_DAYS,
) -> list[dict]:
    """Scan historical run data and create amendment proposals.

    Parameters
    ----------
    runs_dir : str
        Path to ``pipeline/data/runs/`` containing per-task JSON outputs.
    output_json : str
        Path to ``pipeline/data/amendment_proposals.json``.
    concerns_md : str
        Path to ``docs/concerns.md``.
    threshold : int
        Minimum number of distinct tasks that must fail on the same test.
    window_days : int
        How far back to look (days).

    Returns
    -------
    list[dict]
        Newly created proposals (may be empty).
    """
    runs_path = Path(runs_dir)
    if not runs_path.is_dir():
        return []

    cutoff = datetime.now(timezone.utc) - timedelta(days=window_days)

    # ── 1. Scan run files for deploy failures ─────────────────────────
    #
    # Each run file records: timestamp, references, summary, outcome,
    # writer, reviewer, deploy (which contains pipeline_stdout/stderr).

    # Key: (test_file, test_name) → list of {refs, summary, run_file, error_snippet}
    failure_map: dict[tuple[str, str], list[dict]] = defaultdict(list)

    for run_file in sorted(runs_path.glob("*.json")):
        try:
            data = json.loads(run_file.read_text())
        except (json.JSONDecodeError, OSError):
            continue

        if data.get("outcome") != "deploy_failed":
            continue

        # Parse timestamp from the run data.
        ts_str = data.get("timestamp", "")
        try:
            # Format: 2026-03-21T14-30-00Z
            run_ts = datetime.strptime(ts_str, "%Y-%m-%dT%H-%M-%SZ").replace(
                tzinfo=timezone.utc
            )
        except ValueError:
            continue

        if run_ts < cutoff:
            continue

        deploy = data.get("deploy") or {}
        stdout = deploy.get("pipeline_stdout", "")
        stderr = deploy.get("pipeline_stderr", "")
        if not stdout and not stderr:
            continue

        failures = parse_test_failures(stdout, stderr)
        # Only care about essential and pipeline test failures.
        protected_failures = [
            f for f in failures if f["category"] in ("essential", "pipeline")
        ]

        refs = tuple(sorted(data.get("references", [])))
        summary = data.get("summary", "")

        for fail in protected_failures:
            key = (fail["test_file"], fail["test_name"])
            failure_map[key].append({
                "refs": refs,
                "summary": summary,
                "run_file": run_file.name,
                "error_snippet": fail.get("error_snippet", ""),
                "timestamp": ts_str,
            })

    # ── 2. Count distinct tasks per test ──────────────────────────────

    existing = _load_proposals(output_json)
    dismissed = {
        (p["test_file"], p["test_name"])
        for p in existing
        if p.get("status") == "dismissed"
    }
    existing_pending_keys = {
        (p["test_file"], p["test_name"])
        for p in existing
        if p.get("status") == "pending"
    }

    new_proposals: list[dict] = []
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    proposal_counter = sum(1 for p in existing if p["id"].startswith("amend-")) + 1

    for (test_file, test_name), occurrences in failure_map.items():
        key = (test_file, test_name)
        if key in dismissed:
            continue

        # Count distinct task reference sets.
        distinct_ref_sets: set[tuple[str, ...]] = set()
        for occ in occurrences:
            distinct_ref_sets.add(occ["refs"])

        if len(distinct_ref_sets) < threshold:
            continue

        # Already have a pending proposal for this test — update it.
        if key in existing_pending_keys:
            for p in existing:
                if (p["test_file"], p["test_name"]) == key and p["status"] == "pending":
                    p["distinct_task_count"] = len(distinct_ref_sets)
                    p["last_seen"] = max(o["timestamp"] for o in occurrences)
                    p["failing_task_summaries"] = list({
                        o["summary"] for o in occurrences if o["summary"]
                    })[:10]
                    p["evidence_run_files"] = list({
                        o["run_file"] for o in occurrences
                    })[:10]
            continue

        # Create a new proposal.
        date_part = datetime.now(timezone.utc).strftime("%Y%m%d")
        proposal_id = f"amend-{date_part}-{proposal_counter:03d}"
        proposal_counter += 1

        timestamps = [o["timestamp"] for o in occurrences]
        proposal = {
            "id": proposal_id,
            "created_at": now_str,
            "status": "pending",
            "test_file": test_file,
            "test_name": test_name,
            "category": "essential" if "essential" in test_file else "pipeline",
            "distinct_task_count": len(distinct_ref_sets),
            "first_seen": min(timestamps),
            "last_seen": max(timestamps),
            "failing_task_summaries": list({
                o["summary"] for o in occurrences if o["summary"]
            })[:10],
            "error_snippet": occurrences[0].get("error_snippet", ""),
            "evidence_run_files": list({
                o["run_file"] for o in occurrences
            })[:10],
        }
        existing.append(proposal)
        new_proposals.append(proposal)

    # ── 3. Persist ────────────────────────────────────────────────────

    _save_proposals(existing, output_json)
    _render_concerns_md(existing, concerns_md)

    if new_proposals:
        logger.warning(
            "Created %d new amendment proposal(s). See %s",
            len(new_proposals), concerns_md,
        )

    return new_proposals
